// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pokxoqjzgdxaxgogdlml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBva3hvcWp6Z2R4YXhnb2dkbG1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2NDQ3NDQsImV4cCI6MjA1MzIyMDc0NH0.tLwVocwVaI6Zmi_bsCrvgWI3-yj9wNN6rJH4EGcBm-c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);