// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktgfpmzjbgduqbamtull.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0Z2ZwbXpqYmdkdXFiYW10dWxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3Mzc3NjUsImV4cCI6MjA1MzMxMzc2NX0.ABx2ZFtlB37GWjXiGXga98txKl1UTz7mbWneItHS5_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);